=== juanfloresrodriguez/actividadesXML/examen/ejercicio2/tienda.dtd
<!ELEMENT tienda (producto+)>


<!ELEMENT producto (nombre, precio, categoria)>
<!ATTLIST producto id CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT categoria (#PCDATA)>

=== juanfloresrodriguez/actividadesXML/examen/ejercicio2/tienda.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE tienda SYSTEM "C:\Users\juane\Documents\GitHub\XML\actividadesXML\examen\ejercicio2\tienda.dtd">

<tienda>

    <producto id="p1">

        <nombre>Manzana</nombre>

        <precio>0.5</precio>

        <categoria>Fruta</categoria>

    </producto>

    <producto id="p2">

        <nombre>Leche</nombre>

        <precio>1.2</precio>

        <categoria>LÃ¡cteos</categoria>

    </producto>

</tienda>
