=== juanfloresrodriguez/actividadesXML/actividad24/articulos.dtd
<!ELEMENT articulos (articulo+)>
<!ELEMENT articulo (nombre,codigo,fabricante)>



<!ELEMENT nombre (#PCDATA)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT fabricante (#PCDATA)>

<!ATTLIST codigo precio CDATA #REQUIRED>
<!--<!ATTLIST codigo precio (11.9  | 5.6 | 7.2) #REQUIRED>-->

=== juanfloresrodriguez/actividadesXML/actividad24/actividad24.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE equipos SYSTEM "articulos.dtd">

<articulos>
    <articulo>
        <nombre>Cremas Manoli</nombre>
        <codigo precio="11.9">11130</codigo>
        <fabricante>Manoli and CO</fabricante>
    </articulo>
    <articulo>
        <nombre>Potajes Chari</nombre>
        <codigo precio="5.6">11002</codigo>
        <fabricante>Alimentaci√≥n Chari</fabricante>
    </articulo>
    <articulo>
        <nombre>Berza gitana</nombre>
        <codigo precio="7.2">11401</codigo>
        <fabricante>Guisos Jerez</fabricante>
    </articulo>
</articulos>
