=== juanfloresrodriguez/actividadesXML/examen/ejercicio3/estudiantes.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="estudiantes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="estudiante" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="fechaNacimiento" type="xs:date"/>
                            <xs:element name="grado" type="xs:string"/>
                            <xs:element name="cursos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="curso" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre" type="xs:string"/>
                                                    <xs:element name="profesor" type="xs:string"/>
                                                    <xs:element name="calificacion">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:decimal">
                                                                <xs:minInclusive value="0.0"/>
                                                                <xs:maxInclusive value="10.0"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== juanfloresrodriguez/actividadesXML/examen/ejercicio3/estudiantes.xml
<?xml version="1.0" encoding="UTF-8" ?>
<estudiantes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="estudiantes.xsd">

    <estudiante>

        <nombre>Juan Pérez</nombre>

        <fechaNacimiento>2000-01-01</fechaNacimiento>

        <grado>Ingeniería Informática</grado>

        <cursos>

            <curso>

                <nombre>Programación</nombre>

                <profesor>María López</profesor>

                <calificacion>8.5</calificacion>

            </curso>

        </cursos>

    </estudiante>

</estudiantes>
